### ISSUE TITLE
Can't authenticate

### ISSUE THREAD

**Issue by Christo44** [aerobatic/aerobatic-cli#2]
Hi, 

I just upgraded the plugin, I can't however use it anymore. Every command produces:
```
/usr/local/lib/node_modules/aerobatic-cli/commands/create.js:68
        let nextCommand;
        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/aerobatic-cli/bin/aero.js:84:25)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```
and the log
```
{"level":"error","message":"Error response from api: {\"message\":\"Not authenticated\",\"code\":\"tokenExpired\",\"statusCode\":401,\"url\":\"/apps/available\",\"headers\":{\"content-type\":\"application/json; charset=utf-8\",\"content-length\":\"94\",\"connection\":\"close\",\"date\":\"Fri, 26 May 2017 16:16:27 GMT\",\"x-amzn-requestid\":\"ab6d5f3f-422e-11e7-aa5e-f1f44740560e\",\"access-control-allow-origin\":\"*\",\"x-amzn-remapped-content-length\":\"94\",\"x-amzn-remapped-connection\":\"close\",\"cache-control\":\"no-cache\",\"etag\":\"W/\\\"5e-yMRHWuVACDR59HHfOcRe5cN6bLA\\\"\",\"x-powered-by\":\"Express\",\"x-amzn-trace-id\":\"sampled=0;root=1-592854db-629c4fc2f0826fd201dee1c1\",\"x-amzn-remapped-date\":\"Fri, 26 May 2017 16:16:27 GMT\",\"x-cache\":\"Error from cloudfront\",\"via\":\"1.1 d3389211a03760b83dfb110cc5d823db.cloudfront.net (CloudFront)\",\"x-amz-cf-id\":\"4BpnnUptfBe6nTuo-9HbUAMqA3Z-kegfGyyv1MwFlND-8rw0bCqrMA==\"}}","timestamp":"2017-05-26T16:16:27.332Z"}
 
```

**Comment by Christo44** [comment]
Thanks David Von Lehman for jumping on this so quick.

FIXED
